-- Inventaire des box réseau (géré dans Paramètres > Logistique > Réseau).
-- Les chantiers référencent ces box par leur id :
--   chantier_logistique.equipements.wifi = { besoin, ids:[<box.id>], pose, depose }

CREATE TABLE IF NOT EXISTS "public"."boxes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "nom" "text",
  "serie" "text",
  "identification" "text",
  "created_at" timestamp with time zone DEFAULT "now"(),
  "updated_at" timestamp with time zone DEFAULT "now"(),
  CONSTRAINT "boxes_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."boxes" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_all_boxes"
  ON "public"."boxes"
  TO "authenticated"
  USING (true) WITH CHECK (true);

GRANT ALL ON TABLE "public"."boxes" TO "anon";
GRANT ALL ON TABLE "public"."boxes" TO "authenticated";
GRANT ALL ON TABLE "public"."boxes" TO "service_role";
