-- Inventaire des imprimantes (géré dans Paramètres > Logistique > Imprimante).
-- Les chantiers référencent ces imprimantes par leur id :
--   chantier_logistique.equipements.imprimante = { besoin: bool, ids: [<imprimante.id>, ...] }

CREATE TABLE IF NOT EXISTS "public"."imprimantes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "marque" "text",
  "model" "text",
  "serie" "text",
  "identification" "text",
  "type" "text",
  "created_at" timestamp with time zone DEFAULT "now"(),
  "updated_at" timestamp with time zone DEFAULT "now"(),
  CONSTRAINT "imprimantes_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "imprimantes_type_check" CHECK (("type" IS NULL) OR ("type" = ANY (ARRAY['achat'::"text", 'location'::"text"])))
);

ALTER TABLE "public"."imprimantes" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_all_imprimantes"
  ON "public"."imprimantes"
  TO "authenticated"
  USING (true) WITH CHECK (true);

GRANT ALL ON TABLE "public"."imprimantes" TO "anon";
GRANT ALL ON TABLE "public"."imprimantes" TO "authenticated";
GRANT ALL ON TABLE "public"."imprimantes" TO "service_role";
