-- Référentiel des unités de distribution du catalogue matières SNCF
-- Source : extraction du catalogue (dédupliqué, ~170 codes uniques)
CREATE TABLE catalogue_unites_distribution (
  code                TEXT PRIMARY KEY,
  designation         TEXT NOT NULL,
  quantite_par_unite  INTEGER NULL  -- nb de pièces par unité de conditionnement (NULL = variable / mesure physique)
);

ALTER TABLE catalogue_unites_distribution ENABLE ROW LEVEL SECURITY;
CREATE POLICY "all" ON catalogue_unites_distribution FOR ALL USING (true) WITH CHECK (true);

INSERT INTO catalogue_unites_distribution (code, designation, quantite_par_unite) VALUES

-- ── Unité de base ─────────────────────────────────────────────────────────────
('EA',  'Unité',                    1),

-- ── Sachets ───────────────────────────────────────────────────────────────────
('SCT',  'Sachet',                  NULL),
('X2',   'Sachet de 2 pièces',      2),
('X3',   'Sachet de 3 pièces',      3),
('X4',   'Sachet de 4 pièces',      4),
('X5',   'Sachet de 5 pièces',      5),
('X6',   'Sachet de 6 pièces',      6),
('X10',  'Sachet de 10 pièces',     10),
('X12',  'Sachet de 12 pièces',     12),
('X20',  'Sachet de 20 pièces',     20),
('X24',  'Sachet de 24 pièces',     24),
('X25',  'Sachet de 25 pièces',     25),
('X50',  'Sachet de 50 pièces',     50),
('X60',  'Sachet de 60 pièces',     60),
('XC',   'Sachet de 100 pièces',    100),
('X2C',  'Sachet de 200 pièces',    200),
('XCC',  'Sachet de 500 pièces',    500),
('XM',   'Sachet de 1000 pièces',   1000),
('SDS',  'Sachet de 100 pièces',    100),
('S12',  'Sachet de 12 pièces',     12),
('SXM',  'Sachet de 10 m',          NULL),
('10S',  'Sachet de 10 sachets',    10),

-- ── Sacs ──────────────────────────────────────────────────────────────────────
('BG',   'Sac',                     NULL),
('SA4',  'Sac de 4 pièces',         4),
('SA5',  'Sac de 5 pièces',         5),
('SA8',  'Sac de 8 pièces',         8),
('S10',  'Sac de 10 pièces',        10),
('S15',  'Sac de 15 pièces',        15),
('S20',  'Sac de 20 pièces',        20),
('S25',  'Sac de 25 pièces',        25),
('S40',  'Sac de 40 pièces',        40),
('S50',  'Sac de 50 pièces',        50),
('SC',   'Sac de 100 pièces',       100),
('S2C',  'Sac de 200 pièces',       200),
('SDC',  'Sac de 250 pièces',       250),
('S3C',  'Sac de 300 pièces',       300),
('S5C',  'Sac de 500 pièces',       500),
('S5K',  'Sac de 5 kg',             NULL),

-- ── Paquets ───────────────────────────────────────────────────────────────────
('PK',   'Paquet',                  NULL),
('TP',   'Paquet de 10 pièces',     10),
('OP',   'Paquet de 2 pièces',      2),
('P4',   'Paquet de 4 pièces',      4),
('P5',   'Paquet de 5 pièces',      5),
('P6',   'Paquet de 6 pièces',      6),
('P7',   'Paquet de 7 pièces',      7),
('P8',   'Paquet de 8 pièces',      8),
('P20',  'Paquet de 20 pièces',     20),
('P22',  'Paquet de 22 pièces',     22),
('P25',  'Paquet de 25 pièces',     25),
('P39',  'Paquet de 39 pièces',     39),
('P40',  'Paquet de 40 pièces',     40),
('P50',  'Paquet de 50 pièces',     50),
('CNP',  'Paquet de 100 pièces',    100),
('P2C',  'Paquet de 200 pièces',    200),
('P6C',  'Paquet de 600 pièces',    600),
('PK2',  'Pain de 10 kg',           NULL),
('PQK',  'Paquet de 1 kg',          NULL),
('PXP',  'Paquet de 10 paires',     10),
('PE5',  'Paquet de 5 ensembles',   5),
('PMI',  'Paquet de 1000 pièces',   1000),
('XRO',  'Paquet de 10 rouleaux',   10),

-- ── Nombres de pièces (sans conditionnement spécifié) ─────────────────────────
('2P',   '2 pièces',    2),
('5P',   '5 pièces',    5),
('10P',  '10 pièces',   10),
('12P',  '12 pièces',   12),
('15P',  '15 pièces',   15),
('20P',  '20 pièces',   20),
('25P',  '25 pièces',   25),
('50P',  '50 pièces',   50),
('CP',   '100 pièces',  100),
('2CP',  '200 pièces',  200),
('MIL',  'Mille pièces', 1000),

-- ── Lots / Sets ───────────────────────────────────────────────────────────────
('SET',  'Set',                 NULL),
('DUO',  'Duo',                 2),
('KIT',  'Kit',                 NULL),
('5B',   'Lot',                 NULL),
('LO1',  'Lot de 1 pièce',      1),
('LOT',  'Lot de 12 pièces',    12),
('LOV',  'Lot de 25 pièces',    25),
('LOC',  'Lot de 500 pièces',   500),
('10',   'Ensemble',            NULL),
('ST2',  'Jeu de 2 pièces',     2),
('ST4',  'Jeu de 4 pièces',     4),
('PR',   'Paire',               2),
('TU2',  'Tube de 2 pièces',    2),

-- ── Boîtes ────────────────────────────────────────────────────────────────────
('BX',   'Boîte',                       NULL),
('O1',   'Boîte de 4 pièces',           4),
('O2',   'Boîte de 5 pièces',           5),
('O3',   'Boîte de 10 pièces',          10),
('O4',   'Boîte de 12 pièces',          12),
('O5',   'Boîte de 20 pièces',          20),
('O6',   'Boîte de 25 pièces',          25),
('O8',   'Boîte de 50 pièces',          50),
('O10',  'Boîte de 100 pièces',         100),
('O11',  'Boîte de 200 pièces',         200),
('O12',  'Boîte de 250 pièces',         250),
('O13',  'Boîte de 300 pièces',         300),
('O15',  'Boîte de 500 pièces',         500),
('B2C',  'Boîte de 200 pièces',         200),
('B8',   'Boîte de 8 pièces',           8),
('B75',  'Boîte de 75 pièces',          75),
('BTX',  'Boîte de 100 pièces',         100),
('BMP',  'Boîte de 1000 pièces',        1000),
('BML',  'Boîte (référence vierge)',     NULL),
('B1X',  'Boîte de 100 scellés',        100),
('2BK',  'Boîte de 5 kg',               NULL),

-- ── Cartons ───────────────────────────────────────────────────────────────────
('CT',   'Carton',                  NULL),
('CT0',  'Carton de 2 pièces',      2),
('CT1',  'Carton de 5 pièces',      5),
('CT2',  'Carton de 10 pièces',     10),
('CT3',  'Carton de 12 pièces',     12),
('CT4',  'Carton de 16 pièces',     16),
('CT5',  'Carton de 20 pièces',     20),
('CT6',  'Carton de 25 pièces',     25),
('CT7',  'Carton de 50 pièces',     50),
('CT8',  'Carton de 100 pièces',    100),
('CT9',  'Carton de 250 pièces',    250),
('C26',  'Carton de 26 pièces',     26),
('C40',  'Carton de 40 pièces',     40),
('C5C',  'Carton de 5 cartons',     NULL),
('CB0',  'Carton de 12 bidons',     NULL),
('CO6',  'Carton de 6 pièces',      6),
('CK4',  'Carton de 20 kg',         NULL),

-- ── Rouleaux ──────────────────────────────────────────────────────────────────
('RO',   'Rouleau',             NULL),
('ROL',  'Roll',                NULL),
('ROC',  'Rouleau de 15 m',     NULL),
('RO1',  'Rouleau de 5 m',      NULL),
('RO2',  'Rouleau de 10 m',     NULL),
('RO3',  'Rouleau de 20 m',     NULL),
('RO4',  'Rouleau de 25 m',     NULL),
('RO5',  'Rouleau de 30 m',     NULL),
('RO6',  'Rouleau de 40 m',     NULL),
('RO7',  'Rouleau de 50 m',     NULL),
('RO8',  'Rouleau de 100 m',    NULL),
('RO9',  'Rouleau de 300 m',    NULL),
('R60',  'Rouleau de 60 m',     NULL),
('2RO',  '2 rouleaux de 20 m',  NULL),

-- ── Couronnes (longueur de câble/fil) ─────────────────────────────────────────
('COM',  'Couronne de 100 m',   NULL),
('CRN',  'Couronne de 43 m',    NULL),
('V1',   'Couronne de 10 m',    NULL),
('V2',   'Couronne de 25 m',    NULL),
('V4',   'Couronne de 50 m',    NULL),
('V6',   'Couronne de 100 m',   NULL),
('V7',   'Couronne de 120 m',   NULL),
('V8',   'Couronne de 200 m',   NULL),
('V9',   'Couronne de 250 m',   NULL),
('V10',  'Couronne de 320 m',   NULL),
('V11',  'Couronne de 455 m',   NULL),
('V12',  'Couronne de 500 m',   NULL),
('V13',  'Couronne de 715 m',   NULL),
('V14',  'Couronne de 1000 m',  NULL),
('R10',  'Couronne de 10 kg',   NULL),
('R20',  'Couronne de 20 pièces', 20),
('R22',  'Couronne de 22 kg',   NULL),
('R25',  'Couronne de 25 pièces', 25),
('COX',  'Collier de 10 pièces', 10),

-- ── Tourets ───────────────────────────────────────────────────────────────────
('5T',   'Touret de 250 m',     NULL),
('6T',   'Touret de 300 m',     NULL),
('7T',   'Touret de 360 m',     NULL),
('8T',   'Touret de 500 m',     NULL),
('9T',   'Touret de 725 m',     NULL),
('11T',  'Touret de 1000 m',    NULL),
('12T',  'Touret de 1200 m',    NULL),
('13T',  'Touret de 1450 m',    NULL),
('16T',  'Touret de 2400 m',    NULL),
('17T',  'Touret de 4800 m',    NULL),
('18T',  'Touret de 43 m',      NULL),

-- ── Bobines ───────────────────────────────────────────────────────────────────
('4A',   'Bobine',              NULL),
('MB2',  'Bobine de 20 m',      NULL),
('MB3',  'Bobine de 25 m',      NULL),
('MB9',  'Bobine de 50 m',      NULL),
('MBA',  'Bobine de 750 m',     NULL),
('BO3',  'Bobine de 30 m',      NULL),
('BO5',  'Bobine de 500 m',     NULL),
('B1K',  'Bobine de 15 kg',     NULL),
('1BT',  'Botte de 10 kg',      NULL),

-- ── Barres / tubes ────────────────────────────────────────────────────────────
('B6M',  'Barre de 6 m',        NULL),
('B2M',  'Barre de 2 m',        NULL),
('BM2',  'Barre de 6 m',        NULL),
('BM5',  'Barre de 4 m',        NULL),
('BM7',  'Barre de 3,5 m',      NULL),
('BA8',  'Barre de 6 mètres',   NULL),
('BA2',  'Barre de 6,74 kg',    NULL),
('T6M',  'Tube de 6 m',         NULL),

-- ── Métriques ─────────────────────────────────────────────────────────────────
('MTR',  'Mètre',           NULL),
('MTK',  'Mètre carré',     NULL),
('DMQ',  'Décimètre cube',  NULL),
('PM2',  'Plaque de 2 m²',  NULL),
('ST',   'Feuille',         NULL),
('10M',  '10 m',            NULL),
('6M',   '6 m',             NULL),
('1M5',  '1,5 m',           NULL),
('LIM',  'Liasse de 25 m',  NULL),

-- ── Conditionnements liquides ─────────────────────────────────────────────────
('CA',   'Bidon',                   NULL),
('FLA',  'Flacon',                  NULL),
('BL2',  'Bidon de 5 litres',       NULL),
('BL4',  'Bidon de 20 litres',      NULL),
('FL4',  'Fût de 209 litres',       NULL),
('FL5',  'Fût de 208 litres',       NULL),
('Z3',   'Fût',                     NULL),
('TL3',  'Tonnelet de 60 litres',   NULL),
('60L',  '60 litres',               NULL),
('LTR',  'Litre',                   NULL),
('Y3',   'Bidon de 3 kg',           NULL),
('Y5',   'Bidon de 5 kg',           NULL),
('Y10',  'Bidon de 20 kg',          NULL),
('Y15',  'Bidon de 50 kg',          NULL),

-- ── Masses ────────────────────────────────────────────────────────────────────
('KGM',  'Kilogramme',      NULL),
('TNE',  'Tonne',           NULL),
('K1K',  '5 kg',            NULL),
('RK3',  'Rouleau de 25 kg', NULL),
('RK4',  'Rouleau de 30 kg', NULL),

-- ── Palettes ──────────────────────────────────────────────────────────────────
('PF',   'Palette',             NULL),
('PFK',  'Palette de 1500 kg',  NULL),

-- ── Divers ────────────────────────────────────────────────────────────────────
('D92',  'Bande',                   NULL),
('BXP',  'Bande de 10 pièces',      10),
('EV',   'Enveloppe',               NULL),
('PO',   'Pochette',                NULL),
('PO3',  'Pochette de 3 pièces',    3),
('CS',   'Caisse',                  NULL),
('CEN',  'Cent pièces',             100);
